### ISSUE TITLE
'Start Cook' service in Fahrenheit

### ISSUE THREAD

**Issue by noharminthat** [andr83/hacs-anova-oven#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The entities objects for the oven correctly detect that I'm running it in Fahrenheit. However, when calling the 'Start Cook' service, the target temperature setting is in Celsius. 

### Describe the solution you'd like

An option somewhere to switch the target temperature to F. Or, even better would have it match whatever mode the oven is already running in. 

### Describe alternatives you've considered

None

### Additional context

None

**Comment by andr83** [comment]
Duplicate #29

**Comment by andr83** [comment]
Support is in the main b ranch now
