### ISSUE TITLE
Implement timer mode

### ISSUE THREAD

**Issue by koshisan** [andr83/hacs-anova-oven#26]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When using the Anova App to send a timer, there are three different modes:

1. Start manually
2. Start automatically
3. Start immediately (when the pre-heating begins)

This option seems to be missing from the service

### Describe the solution you'd like

An additional option for the service would be great.

### Describe alternatives you've considered

Well - there pretty much isn't any aparat from leaving things as they are/using the app instead of HA ;)

### Additional context

No required - I think.

**Comment by koshisan** [comment]
Any chance to get this implemented?
While it doesn't matter for most of the stuff, I often cook things that require only a short, precise timing (Eggs, Bread Rolls, etc.)...

**Comment by andr83** [comment]
I will take a look.

**Comment by andr83** [comment]
Implemented in the main branch. But need to do some tests. Will appreciate if someone will test too.

**Comment by koshisan** [comment]
Thank you very much! I tried it today and timer mode is working as expected!

Doing my tests I found two other things, however:

1. I cannot edit my scripts I made with the older version through the gui. The reason seems to be that one temperature value was renamed. No issue for me, since I found out what the issue was pretty much immediately and YAML always works. But maybe something to keep in mind when renaming things...
2. At least with my settings the oven fails to reach its target humidity. Comparing with cooks through the app I believe this is due to HA using "realtive-humidity" as steam generator mode. The app is using "steam-percentage". Is the required parameter currently exposed? Note that this is not a sous vide cook, but baking bread rolls with 80% steam at 210C....

**Comment by andr83** [comment]
Thank you for feedback. About issues:

1. Yes, agree about renaming but I prefer to keep naming consistent and predictable. I will add it to breaking changes notes to release of course.
2. You are agree, I usually use steam generator only in sous vide mode and app setup it as "realtive-humidity". But for non sous vide it should be set to "steam-percentage". I fixed it, changes in the main branch.

**Comment by koshisan** [comment]
Thank you! I updated it and now steam seems to be generated as expected! However, I cannot really be 100% sure, since the humidity sensor now reports "unknown" - is that expected with steam-percentage mode?

**Comment by andr83** [comment]
is it showing in the integration or application?

**Comment by koshisan** [comment]
Neither! I the app does show "steam x%", but it is unclear if its an actual measurement or just the value it is trying to reach...

**Comment by andr83** [comment]
Ok, will take a look later

**Comment by andr83** [comment]
Could not reproduce it. It shows for me in both correct values for different modes. May be you can add description step by step how to reproduce it.

**Comment by koshisan** [comment]
Hmm, I am not sure how though. Basically my sensor values look like this:
![grafik](https://github.com/andr83/hacs-anova-oven/assets/40839790/43a02596-a0d9-4a4b-ba13-9c18cde57014)
After starting the oven with this script:
![grafik](https://github.com/andr83/hacs-anova-oven/assets/40839790/a98bf833-4055-41c6-b640-280bdd9547e3)
As you can see, humidity is unkown.
It seems the value is not present when the generator mode is "steam-percentage":
![grafik](https://github.com/andr83/hacs-anova-oven/assets/40839790/d089812a-6072-43c2-8d49-518a5ccf7752)
However, like I said: I am unsure if that is a bug or by design...

**Comment by andr83** [comment]
Interesting, can not reproduce. Can you try re-download integration and if will reproduce enable debugging for integration and send me logs?
