### ISSUE TITLE
Imperial units

### ISSUE THREAD

**Issue by jamesjhfadler** [andr83/hacs-anova-oven#29]
### System Health details

ommited

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have found an issue that you might or might not have any control over.

I am in the US and have setup the oven to use imperial units (F) for temp

The integration uses metric temp units (C).

When I call the start_cook service and attempt to use sous vide mode, I get an unknown error for any temp value above 100.
When I sous vide mode and set the temp below 100, the service succeeds.

However,the oven temp is set to 100 (F), not 100 (C), due to my units setting on the oven.

So, as a result of this I can never get sous vide above 100 (F).

Are there settings in the python files or yaml files that I can change to allow for imperial units?

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
ommited
```

**Comment by andr83** [comment]
@jamesjhfadler the support in the master branch. If you can test it before release would appreciate.

**Comment by jamesjhfadler** [comment]
I will not be able to test for a month or so.
