### ISSUE TITLE
What's the hacs repo?  The readme link disappeared?

### ISSUE THREAD

**Issue by Maxxell** [andr83/hacs-anova-oven#41]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Sorry if I am missing something basic, but I cant even install this because the HACS installation steps say install "THIS" repo, but there's no link in the word "THIS".  What's the repo to get at this package?

### Reproduction steps

1. Have Home Assistant
2. Have HACS
3. Try to install this package
4. Visit this page to get instructions
5. Get sad when you realize there's no actual repo listed
...

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by andr83** [comment]
There is a link for repo in the head:

<img width="505" alt="Screenshot 2024-08-23 at 16 10 53" src="https://github.com/user-attachments/assets/f5a9cf8d-9914-4020-b203-75adc77ca1b5">

**Comment by Maxxell** [comment]
Thank you!

**Comment by Maxxell** [comment]
Spoke too soon...  When I enter https://github.com/andr83/hacs-anova-oven in the "Add repository" part of HACS, I get no repositories found...

**Comment by andr83** [comment]
Because you add a wrong link. You should add to custom repositories not link to git project but copy git link like here: 
<img width="484" alt="Screenshot 2024-08-23 at 16 22 31" src="https://github.com/user-attachments/assets/6c5575ad-5c03-4720-9113-c3a48ca07eb4">

**Comment by Maxxell** [comment]
100%  You were right.

Thanks amigo!
