### ISSUE TITLE
Humidity control on start cooking

### ISSUE THREAD

**Issue by mcolyer** [andr83/hacs-anova-oven#7]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not applicable 

### Describe the solution you'd like

Ability to set humidity level

### Describe alternatives you've considered

Can't control it currently

### Additional context

None

**Comment by andr83** [comment]
Fixed in v0.0.2
