### ISSUE TITLE
Multistage cooks

### ISSUE THREAD

**Issue by mcolyer** [andr83/hacs-anova-oven#8]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It would be nice to be able to submit multi-step cooks to a service that handles that. 

### Describe the solution you'd like

I think it takes all the same inputs as start cooks but as an array.

### Describe alternatives you've considered

Don't really think there's an easy workaround for this as cooks move between stages based on events on the oven (timer or temperature set points being reached)

### Additional context

N/A

**Comment by andr83** [comment]
The only reason I didn't add multistage cooking is a problem with UI for services in HA. There are no options to create multi stages description except raw coding in yaml. Possible workarounds:

1. Use yaml configuration for stages. 
2. Have service configuration template with 3-4 preconfigured stages. 
3. Configure stages in the anova app and store them as presets.

**Comment by mcolyer** [comment]
I was thinking yaml would be fine, this is pretty advanced but you bring up
a good point the UI isn't great. So maybe there should be two services so
that there's an "easy" mode?

**Comment by andr83** [comment]
Done in the master. Added new service "Custom cooking" where is possible to add raw stages configuration for Anova. Take current cooking as raw configuration is possible from "raw_stages" attribute on the "Mode" sensor.
